In [157]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Warm-up (4 points)

## 1.1 Creating Matrices (0.25 points)

Create 4 matrices
- A - a "checkerboard" matrix of zeros and ones, size 6x3, with the top-left value (A[0][0]) equal to 1,
- В - a matrix of numbers from 1 to 24, arranged in a snake-like pattern, size 6x4,
- C - a matrix of random integers from 2 to 10 (inclusive), size 4x3,
- D - a matrix of zeros with ones on the main diagonal, size 4x4.

**Create a “patchwork” matrix S from these matrices**

A В

С D

using **only standard** numpy operations. Do not use Comprehensions.

Then, append matrix **F** of size 10x2 filled with zeros to the resulting matrix **S** to create matrix **G**:

S F

Note: When we say a matrix has a size of x by y, x is the number of rows, and y is the number of columns.

In [ ]:

# Step 1: Create matrix A (6x3 checkerboard)
A = np.tile([[1, 0, 1], [0, 1, 0]], (3, 1))

# Step 2: Create matrix B (6x4 snake-like)
B = np.zeros((6, 4), dtype=int)
for i in range(6):
    B[i] = np.arange(i * 4 + 1, (i + 1) * 4 + 1)[::(-1) ** i]  # Create snake pattern

# Step 3: Create matrix C (4x3 random integers from 2 to 10)
C = np.random.randint(2, 11, (4, 3))

# Step 4: Create matrix D (4x4 identity)
D = np.eye(4, dtype=int)

# Step 5: Combine matrices to form the patchwork matrix S
top = np.hstack((A, B))  # Top part: A | B
bottom = np.hstack((C, D))  # Bottom part: C | D
S = np.vstack((top, bottom))  # Combine top and bottom

# Step 6: Create matrix F (10x2 zeros)
F = np.zeros((10, 2), dtype=int)

# Step 7: Append F to S to form matrix G
G = np.hstack((S, np.vstack((F, np.zeros((S.shape[0] - F.shape[0], 2), dtype=int)))))

# Display matrices using pandas for better visualization
print("Matrix A:")
print(pd.DataFrame(A))

print("\nMatrix B:")
print(pd.DataFrame(B))

print("\nMatrix C:")
print(pd.DataFrame(C))

print("\nMatrix D:")
print(pd.DataFrame(D))

print("\nMatrix F:")
print(pd.DataFrame(F))

print("\nPatchwork Matrix S:")
print(pd.DataFrame(S))

print("\nFinal Matrix G:")
print(pd.DataFrame(G))


## 1.2 Finding the Nearest Neighbor (0.25 points)

Implement a function that takes a matrix **X** and a number **a** and returns the element in the matrix closest to the given number.
   
For example, for **X = np.arange(0, 10).reshape((2, 5))** and **a = 3.6**, the answer will be 4. You can only use basic numpy functions, **do not use loops**.

In [41]:
def find_nearest_neighbour(X,a):
    diff = np.abs(X - a).argmin()
    return X.flat[diff]

X = np.arange(0, 10).reshape((2, 5))
a = 2.3

result = find_nearest_neighbour(X,a)

print(result)

2


## 1.3 Very Strange Neural Network (0.25 points)

Implement a strange neural network. The network should:

- Square matrix **A** (the weight matrix) of size N x N.
- In the first transformation, multiply a vector **X** of length N (feature vector) by the weight matrix **A^2** (the output will be a new vector).
- In the second transformation, multiply the resulting vector by vector **b** (weight vector) of size N to produce a scalar value.

Assume that all elements in matrices and vectors are floating-point numbers.

In [ ]:
# Create your own data for an example, with N >= 4
A = np.random.rand(2,2)
b = np.random.rand(1,2)
X = np.random.rand(2,1)

def very_strange_neural_network(A, b, X):
    A_squared = np.dot(A, A)
    
    intermediate_vector = np.dot(A_squared, X)
    
    result = np.dot(b, intermediate_vector)
    return result

print(very_strange_neural_network(A,b,X))

[[0.96489273]]


## 1.4 The Jungle Calls! (0.25 points)

You are given a matrix **M**, a map of an impassable jungle terrain created by Lara Croft. Each cell in the map is an integer representing the height above sea level (if positive) in meters or the sea depth (if negative) in meters in a one-meter-by-one-meter area of the map. If the number is 0, it represents land - a shoreline.

You need to calculate:
- The total area of cells in the sea where the depth is greater than 5 (in m^2).
- The total volume of water on the map (in m^3).
- The maximum height above sea level on this map (in m).

In [84]:
def find_deep_sea_area(M):
    return np.sum(M < -5)

def find_water_volume(M):
    return -np.sum(M[M < 0])

def find_max_height(M):
    return np.amax(M)

In [87]:
M = np.array([
    [-7, -8, -1, 0],
    [-4, -3, 1, 19],
    [-2, 0, 4, 25],
    [-1, 3, 6, 9]
])

# simple check for the example above
assert np.isclose(find_deep_sea_area(M), 2)
assert np.isclose(find_water_volume(M), 26)
assert np.isclose(find_max_height(M), 25)

print("Total sea area on the map -", find_deep_sea_area(M), "м^2")
print("Total water volume on the map -", find_water_volume(M), "м^3")
print("Maximum elevation on the map -", find_max_height(M), "м")


Total sea area on the map - 2 м^2
Total water volume on the map - 26 м^3
Maximum elevation on the map - 25 м


## 1.5 Treasure Islands (0.25 points)


The function takes an array **a** of zeros and ones as input. Count the number of consecutive blocks of ones (islands) in the array. Only basic numpy functions are allowed, **no loops**.

Hint: check what `np.diff` does.

In [28]:
def count_all_islands(a):
    transitions = np.diff(a)  # Differences between consecutive elements
    return np.sum(transitions == 1) + (a[0] == 1)

In [80]:
# можно подставить свой пример

a = np.array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1])

# простая проверка для примера выше
assert count_all_islands(a) == 4
print(count_all_islands(a))


4


## 1.6 Masquerade (0.25 points)

The input is a 2D matrix **X** filled with floating-point numbers and a floating-point number **a**. Replace all cells in the matrix greater than **a** with the average value of the elements in **X**.

**You must** use basic numpy functions, **no loops**.

In [71]:
def swap_mask_for_average(X, a):
    avg = np.average(X)
    M[M > a] = avg
    return M

In [79]:
# You can create your own example.
M = np.array([
    [-7, -3, -1, 0],
    [-4, -3, 1, 19],
    [-2, 0, 4, 25],
    [-1, 3, 6, 9]
])
a = 5
print(np.average(M))
# simple check for the example above
assert np.allclose(swap_mask_for_average(M, a),
                   np.array([
                       [-7, -3, -1, 0],
                       [-4, -3, 1, 2],
                       [-2, 0, 4, 2],
                       [-1, 3, 2, 2]
                   ]))
swap_mask_for_average(M, a)

2.875


array([[-7, -3, -1,  0],
       [-4, -3,  1,  2],
       [-2,  0,  4,  2],
       [-1,  3,  2,  2]])

## 1.7 Hot on the Trails (0.25 points)

The input is a square matrix **M**. Calculate the difference between the sum along the main diagonal and the secondary diagonal.

Only basic numpy functions are allowed, **no loops**.

Hint: look up `np.trace`.

In [101]:
import numpy as np
np.trace(np.eye(3))
a = np.random.randint(4,11,(2,2))
print(a)
np.trace(a)

[[9 7]
 [6 7]]


np.int64(16)

In [ ]:
def count_trace_diff(M):
    mdiag = np.trace(M)
    sediag = np.trace(np.fliplr(M))
    return mdiag - sediag

In [109]:
# You can create your own example.
M = np.array([
    [-7, -3, -1, 0],
    [-4, -3, 1, 19],
    [-2, 0, 4, 25],
    [-1, 3, 6, 9]
])
# simple check for the example above
assert np.allclose(count_trace_diff(M), 3)

count_trace_diff(M)

np.int64(3)

## 1.8 King of the Hill (0.25 points)

The input is a vector a of size N. Using addition, concatenation, and broadcasting, create a symmetric matrix of size 2N x 2N with the maximum value in the center and decreasing values toward the edges.

Example: a = (0, 1, 2)

Result:

0 1 2 2 1 0 \\
1 2 3 3 2 1 \\
2 3 4 4 3 2 \\
2 3 4 4 3 2 \\
1 2 3 3 2 1 \\
0 1 2 2 1 0 \\

In [155]:
def create_mountain(a):
    base = a[:, None] + a
    top_half = np.concatenate([base, base[:, ::-1]], axis=1)
    full_matrix = np.concatenate([top_half, top_half[::-1, :]], axis=0)
    return full_matrix

In [156]:
# You can create your own example.
a = np.array([0, 1, 2, 3,4])

create_mountain(a)

array([[0, 1, 2, 3, 4, 4, 3, 2, 1, 0],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [2, 3, 4, 5, 6, 6, 5, 4, 3, 2],
       [3, 4, 5, 6, 7, 7, 6, 5, 4, 3],
       [4, 5, 6, 7, 8, 8, 7, 6, 5, 4],
       [4, 5, 6, 7, 8, 8, 7, 6, 5, 4],
       [3, 4, 5, 6, 7, 7, 6, 5, 4, 3],
       [2, 3, 4, 5, 6, 6, 5, 4, 3, 2],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [0, 1, 2, 3, 4, 4, 3, 2, 1, 0]])

## 1.9 Monochrome Photograph 9x12 (0.5 points)

The input is a 2D matrix **P** of size N x M filled with numbers from 0 to 255, representing a grayscale photograph, and a natural number **C**. You need to produce a matrix of size (N - C + 1) x (M - C + 1), where each cell is the average value of the corresponding sub-matrix of size **C x C**. Essentially, this will apply a simple blur effect (slightly reducing its size).

In [158]:
def custom_blur(P, C):
    # Shape of the output matrix
    N, M = P.shape
    output_shape = (N - C + 1, M - C + 1)
    
    # Stride-based sub-matrices using broadcasting to calculate averages
    sub_matrices = np.lib.stride_tricks.sliding_window_view(P, (C, C))
    return sub_matrices.mean(axis=(-2, -1))  # Average over each CxC sub-matrix



In [159]:
# Example matrix and kernel
P = np.arange(0, 12).reshape((3, 4))
kernel = 2

# Applying the blur function
result = custom_blur(P, kernel)

# Printing the result
print(result)

# Simple check for validation
assert np.allclose(result, np.array([[2.5, 3.5, 4.5], [6.5, 7.5, 8.5]]))

[[2.5 3.5 4.5]
 [6.5 7.5 8.5]]


## 1.10 Validation Function (0.75 points)

The input to the function is an arbitrary number (>2) of tuples representing the shapes of different matrices. The function should return True if the matrices can be sequentially added together (possibly using broadcasting), and False otherwise.

In [160]:
def check_successful_broadcast(*matrices):
    # Helper function to check broadcasting compatibility between two shapes
    def are_shapes_compatible(shape1, shape2):
        # Reverse the shapes to align trailing dimensions
        shape1, shape2 = shape1[::-1], shape2[::-1]
        for i in range(max(len(shape1), len(shape2))):
            dim1 = shape1[i] if i < len(shape1) else 1
            dim2 = shape2[i] if i < len(shape2) else 1
            if dim1 != dim2 and dim1 != 1 and dim2 != 1:
                return False
        return True

    # Sequentially check compatibility
    current_shape = matrices[0]
    for next_shape in matrices[1:]:
        if not are_shapes_compatible(current_shape, next_shape):
            return False
        # Update the current shape to the resulting broadcasted shape
        current_shape = tuple(
            max(dim1, dim2) if dim1 != 1 and dim2 != 1 else max(dim1, dim2)
            for dim1, dim2 in zip(
                (1,) * (len(next_shape) - len(current_shape)) + current_shape,
                (1,) * (len(current_shape) - len(next_shape)) + next_shape
            )
        )
    return True

In [ ]:
# I test with your examples
print(check_successful_broadcast((5, 6, 7), (6, 7), (1, 7)))
print(check_successful_broadcast((2,5,8),(2,1,1)))


True


## 1.11 Pairwise Distances (0.75 points)

The input is matrices A of size m x k and B of size n x k. Create a matrix of size m x n containing pairwise Euclidean distances.

Only use basic functions, do not use loops or third-party libraries. Broadcasting will probably be useful. The solution must be **in one line**, following all code style rules.

In [169]:
def pairwise_distances(A, B):
    return ((A[:, None, :] - B[None, :, :]) ** 2).sum(axis=2) ** 0.5


In [170]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8], [9, 10]])

pairwise_distances(A, B)

array([[ 5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  5.65685425,  8.48528137]])

MY EXPLAIN :


# 2. Data Experiment Processing (3 points)

Ladies and gentlemen, now we're going to learn to use libraries for data analysis in real-life scenarios!

**The reason behind this section is simple**: many students in the Faculty of Physics and Mathematics still rely on Excel, calculators, or pen and paper even in their second or third semesters. Our goal is to introduce another method for conducting laboratory work with a much lower entry barrier than Excel itself. We hope this motivates some to explore these handy libraries further.

*Data sponsor for this section - blacksamorez. Without them, five happy semesters of labs would have been far less joyful...*

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##  2.1. Problem Statement and Data

Let's assume we have a gyroscope with a weight attached to its axis on an arm (see the diagram for a quick understanding, and you can find more details in the [laboratory manual](https://lib.mipt.ru/book/267519/), volume 1, p.160). Due to the weight, the gyroscope begins to slowly [precess](https://en.wikipedia.org/wiki/Precession), i.e., it rotates around the vertical axis with a relatively constant frequency.

We'll work through part of this lab, primarily focusing on data processing and plotting graphs.

<center><img src='https://drive.google.com/uc?export=view&id=1KfYQ0hKYRDhi5uk7C8lNffZBNy8NF7nu' width=600>

Diagram of the gyroscope with the attached weight G and arm C</center>

In [224]:
data = pd.read_csv('data_numpy_lab.csv')
data.head()

Unnamed: 0  N  t, sec  sigma_t, sec  mass, gramm  length, cm  phi, rad
0           1  4     268             1        180.0       121.0      0.16
1           2  4     264             1        180.0       121.0      0.18
2           3  4     275             1        180.0       121.0      0.16
3           4  4     263             1        180.0       121.0      0.17
4           5  4     267             1        180.0       121.0      0.17

## 2.2 Working with Data

The columns in the dataframe are as follows:

- N: Number of full gyroscope rotations in the experiment;
- t, in seconds: Time of the experiment;
- σ_t: Measurement error in time;
- mass: Mass of the weight attached to the arm on the gyroscope;
- length: Length of the previously mentioned arm;
- phi: Angle in radians by which the arm dropped during the experiment. This will help us estimate the effect of friction in the gyroscope on precession.

Since physicists like to work with properly dimensioned quantities, convert the mass columns to kilograms and length to meters. Then rename all columns to exclude references to units—use only the names of physical quantities.

In [ ]:
data['mass, gramm']= data['mass, gramm'] / 1000
data['length, cm'] = data['length, cm'] /100



In [ ]:
data.rename(columns={"t, sec" : 't', 'sigma_t, sec' : 'sigma_t', 'mass, gramm' : 'mass',
       'length, cm' : 'length', 'phi, rad' : 'phi'}, inplace=True)
data.head()

Unnamed: 0  N    t  sigma_t  mass  length   phi
0           1  4  268        1  0.18    1.21  0.16
1           2  4  264        1  0.18    1.21  0.18
2           3  4  275        1  0.18    1.21  0.16
3           4  4  263        1  0.18    1.21  0.17
4           5  4  267        1  0.18    1.21  0.17

In [229]:
assert data.mass.mean() < 0.3
assert np.allclose(data['length'].mean(), 1.155)
# assert all(' ' not in column for column in data.columns)


Add new columns to the dataframe with the corresponding names and values, calculated using these formulas:

`omega`: $\Omega = 2 \pi \cdot \frac{N}{t}$

`sigma_omega`: $\sigma_{\Omega} = \Omega / t \cdot \sigma_t$

`omega_down`: $\Omega_{down} = \varphi / t$

`sigma_down`: $\Omega_{down} \cdot \sigma_t / t$

`momentum`: $M = m \cdot g \cdot l$ (`g = 9.8 м/с^2`)

`momentum_down`: $M_{down} = m \cdot \frac{\varphi}{t^2} \cdot l^2$

`sigma_momentum`: $\sigma_{M} = M_{down} \cdot 2 \cdot \frac{\sigma_t}{t}$